services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - .nuxt:/app/.nuxt
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
    command: npm run dev
  # Production service
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - HOST=0.0.0.0
  #     - PORT=3000
  #   restart: unless-stopped


  # docker compose up --build
