FROM node:22-slim

WORKDIR /app


# Copy package files
COPY package.json pnpm-lock.yaml* ./

# Install dependencies
RUN npm config set fetch-retries 5 && \
    npm config set fetch-retry-mintimeout 20000 && \
    npm config set fetch-timeout 300000 && \
    npm install

# Copy project files
COPY . .

# Expose port
EXPOSE 3000

# Set environment
ENV HOST=0.0.0.0
ENV PORT=3000
ENV NODE_ENV=development

# Start development server
CMD ["npm", "run", "dev"]
