package gojasperxml

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"

	"github.com/jung-kurt/gofpdf"
)

type pdfGenerator struct {
	pdf    *gofpdf.Fpdf
	margin float64
	pageW  float64
	pageH  float64
}

func newBasicGenerator() *pdfGenerator {
	return &pdfGenerator{
		margin: 10,
	}
}

func (g *pdfGenerator) Generate(data []map[string]interface{}, params ...interface{}) ([]byte, error) {
	if len(data) == 0 {
		return nil, nil
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pageW, pageH := pdf.GetPageSize()

	g.pdf = pdf
	g.pageW = pageW
	g.pageH = pageH

	pdf.SetMargins(g.margin, g.margin, g.margin)
	pdf.AddPage()

	pdf.SetFont("Helvetica", "B", 16)
	pdf.Cell(pageW-2*g.margin, 10, "PURCHASE ORDER")
	pdf.Ln(10)

	firstRow := data[0]

	pdf.SetFont("Helvetica", "", 10)

	getStr := func(key string) string {
		if v, ok := firstRow[key]; ok {
			return fmt.Sprintf("%v", v)
		}
		return ""
	}

	pdf.Cell(40, 5, "No. PO")
	pdf.Cell(5, 5, ":")
	pdf.Cell(pageW-2*g.margin-45, 5, getStr("no"))
	pdf.Ln(6)

	pdf.Cell(40, 5, "Tanggal")
	pdf.Cell(5, 5, ":")
	pdf.Cell(pageW-2*g.margin-45, 5, getStr("tanggal"))
	pdf.Ln(10)

	pdf.SetFont("Helvetica", "B", 11)
	pdf.Cell(pageW-2*g.margin, 1, "")
	pdf.SetLineWidth(0.5)
	pdf.Line(g.margin, pdf.GetY(), pageW-g.margin, pdf.GetY())
	pdf.Ln(3)

	pdf.SetFont("Helvetica", "B", 10)
	pdf.Cell(40, 6, "SUPPLIER")
	pdf.Ln(6)

	pdf.SetFont("Helvetica", "", 10)
	pdf.Cell(pageW-2*g.margin, 5, getStr("supplier"))
	pdf.Ln(5)
	pdf.Cell(pageW-2*g.margin, 5, getStr("alamat"))
	pdf.Ln(5)
	pdf.Cell(pageW-2*g.margin, 5, "Telp: "+getStr("telp"))
	pdf.Ln(5)

	pdf.Ln(5)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.Cell(40, 6, "SHIP TO / STORE")
	pdf.Ln(6)

	pdf.SetFont("Helvetica", "", 10)
	pdf.Cell(pageW-2*g.margin, 5, getStr("store"))
	pdf.Ln(10)

	colW := []float64{12, 70, 22, 32, 32, 22}
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(220, 220, 220)
	headers := []string{"No", "Nama Produk", "Qty", "Harga", "Total", "Sat"}
	for i, h := range headers {
		pdf.CellFormat(colW[i], 7, h, "1", 0, "C", true, 0, "")
	}
	pdf.Ln(0)
	pdf.SetFillColor(255, 255, 255)

	pdf.SetFont("Helvetica", "", 8)
	pdf.Ln(0)
	for idx, row := range data {
		productName := fmt.Sprintf("%v", row["namaItem"])
		if len(productName) > 32 {
			productName = productName[:29] + "..."
		}

		fmtStr := func(key string) string {
			if v, ok := row[key]; ok {
				return formatVal(v)
			}
			return "0"
		}

		border := "1"
		pdf.CellFormat(colW[0], 8, fmt.Sprintf("%d", idx+1), border, 0, "C", false, 0, "")
		pdf.CellFormat(colW[1], 8, productName, border, 0, "L", false, 0, "")
		pdf.CellFormat(colW[2], 8, fmtStr("qty"), border, 0, "C", false, 0, "")
		pdf.CellFormat(colW[3], 8, fmtStr("harga"), border, 0, "R", false, 0, "")
		pdf.CellFormat(colW[4], 8, fmtStr("total"), border, 0, "R", false, 0, "")
		pdf.CellFormat(colW[5], 8, fmtStr("sat"), border, 0, "C", false, 0, "")
		pdf.Ln(0)
	}
	pdf.Ln(5)

	subtotalX := pageW - g.margin - 60

	pdf.SetFont("Helvetica", "", 9)
	pdf.Cell(subtotalX-g.margin, 5, "Subtotal")
	pdf.CellFormat(60, 5, getStr("subtotal"), "1", 0, "R", false, 0, "")
	pdf.Ln(5)

	if v, ok := firstRow["diskon"].(float64); ok && v > 0 {
		pdf.Cell(subtotalX-g.margin, 5, "Diskon")
		pdf.CellFormat(60, 5, "-"+formatVal(v), "1", 0, "R", false, 0, "")
		pdf.Ln(5)
	}

	if v, ok := firstRow["ppn"].(float64); ok && v > 0 {
		pdf.Cell(subtotalX-g.margin, 5, "PPN (11%)")
		pdf.CellFormat(60, 5, getStr("ppn"), "1", 0, "R", false, 0, "")
		pdf.Ln(5)
	}

	pdf.SetFont("Helvetica", "B", 10)
	pdf.Cell(subtotalX-g.margin, 6, "TOTAL")
	pdf.CellFormat(60, 6, getStr("grandtotal"), "1", 0, "R", false, 0, "")
	pdf.Ln(10)

	pdf.SetFont("Helvetica", "", 9)
	pdf.Cell(60, 5, fmt.Sprintf("Payment Terms: %s days", getStr("paymentTerms")))
	pdf.Ln(5)
	pdf.Cell(60, 5, fmt.Sprintf("Payment Mode: %s", getStr("paymentMode")))
	pdf.Ln(10)

	pdf.Ln(15)
	pdf.SetFont("Helvetica", "", 9)
	pdf.CellFormat((pageW-2*g.margin)/2-5, 1, "", "0", 0, "C", false, 0, "")
	pdf.Line(pdf.GetX(), pdf.GetY(), pdf.GetX()+(pageW-2*g.margin)/2-5, pdf.GetY())
	pdf.Ln(1)
	pdf.Cell((pageW-2*g.margin)/2-5, 5, "Approved By")
	pdf.CellFormat(5, 5, "", "0", 0, "C", false, 0, "")
	pdf.Cell((pageW-2*g.margin)/2-5, 5, "Received By")
	pdf.Ln(15)

	pdf.SetFont("Helvetica", "", 8)
	approvedBy := getStr("approvedBy")
	if approvedBy != "" {
		pdf.Cell((pageW-2*g.margin)/2-5, 4, approvedBy)
	}
	pdf.Cell((pageW-2*g.margin)/2-5, 4, "")
	pdf.Ln(0)

	pdf.SetFont("Helvetica", "I", 7)
	pdf.SetTextColor(128, 128, 128)
	pdf.Cell(pageW-2*g.margin, 4, "Generated by go-jasperxml")
	pdf.Ln(0)

	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, fmt.Errorf("failed to generate PDF: %w", err)
	}

	return buf.Bytes(), nil
}

func formatVal(v interface{}) string {
	switch val := v.(type) {
	case string:
		return val
	case float64:
		if val == float64(int(val)) {
			return strconv.FormatFloat(val, 'f', 0, 64)
		}
		return formatNumber(val)
	case int:
		return strconv.Itoa(val)
	case int64:
		return strconv.FormatInt(val, 10)
	default:
		return fmt.Sprintf("%v", val)
	}
}

func formatNumber(n float64) string {
	s := fmt.Sprintf("%.2f", n)
	if idx := strings.Index(s, "."); idx > 0 {
		intPart := s[:idx]
		decPart := s[idx:]
		length := len(intPart)
		if length == 0 {
			return s
		}
		var result strings.Builder
		for i := 0; i < length; i++ {
			if i > 0 && (length-i)%3 == 0 {
				result.WriteString(".")
			}
			result.WriteByte(intPart[i])
		}
		return result.String() + decPart
	}
	return s
}